service: studentdemo

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  package:
    individually: true

functions:
  test:
    handler: dist/handler.test
    events:
      - http: GET test

