service: studentdemo

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  package:
    individually: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  get-test:
    handler: src/lambdas/http/get-test.handler
    events:
      - http: GET test
  post-test:
    handler: src/lambdas/http/post-test.handler
    events:
      - http: POST test

