swagger: '2.0'
info:
  version: 0.0.1
  title: Messages
  description: Serverless Lab API
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
paths:
  '/test':
    get:
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          'Fn::Sub': >-
            arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:122517921916:function:andreas-hagman-serverlesslab-dev-GetTest/invocations
      responses:
        '200':
          description: ''
          schema:
            type: '#/definitions/GetTestModel'
        default:
          description: ''
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          'Fn::Sub': >-
            arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:122517921916:function:andreas-hagman-serverlesslab-dev-PostTest/invocations
      responses:
        '200':
          description: ''
          schema:
            type: '#/definitions/PostTestModel'
        default:
          description: ''
          schema:
            $ref: '#/definitions/ErrorModel'
definitions:
  ErrorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  PostTestModel:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  GetTestModel:
    type: object
    required:
      - message
    properties:
      message:
        type: string